### ISSUE TITLE
Move in World Coordinate

### ISSUE THREAD

**Issue by nyan987** [glumb/robot-gui#3]
Hi, your code is very useful for me, thanks for sharing.

I need to modify few things regarding the movement on world coordinates and how to convert it to the TCP  (local) coordinate. Could you give me some direction on which method/function to do it? I had a trouble to find it. Thanks

**Comment by glumb** [comment]
Well, sorry for the super late reply. I overlooked your question somehow.
Inverse kinematics is calculated here: https://github.com/glumb/robot-gui/blob/master/js/InverseKinematic.js
