### ISSUE TITLE
About  TCP rotating XYZ

### ISSUE THREAD

**Issue by natdon** [glumb/robot-gui#4]
Hello!
         When the X axis is rotated, set the X value to 1.55, the angle of the A3 is 86, and when the X value continues to increase to 1.65, the A3 value is -89, then the machine will swirl quickly. How to fix this problem?

**Comment by glumb** [comment]
A3 will only operate in the range of +-90 degree. The idea is that you can reach all poses with this range. (Not without a reconfiguration of the wrist in some positions though)
The goal is to implement proper robot configurations that circumvent this issue. Currently one configuration is hardcoded. 

If you need a smooth motion over these boundaries you may need to hack this yourself. Look for the kinematics.cpp. At the end you can check if the angle is <=0 and add something like angle[3] = 90*Deg2Rad+90*Deg2Rad+angle[3] (basically changing the range of motion from  -90/90 to 0/180. not tested. ) You also have to flip the axis 4 then.

**Comment by glumb** [comment]
@lo-th should work now
