### ISSUE TITLE
Max/min angle rotate with joint, should stay relative to parent?

### ISSUE THREAD

**Issue by i-make-robots** [glumb/robot-gui#8]
as I understand it... the yellow cylinder represents a joint.  The green/red portion represents the min/max angle.  The line between min & max is the angle where green and red meet.

When I move the TCP the min/max angles are moving relative to the current angle.  It doesn't correctly display current angle relative to min & max.

**Comment by glumb** [comment]
![B2315B25-6C15-41E4-AA25-C6A9FB98DA21](https://user-images.githubusercontent.com/3062564/58902368-4263d000-8703-11e9-9aa7-c7b1c192dd23.jpeg)
The way angle limits are displayed is indeed suboptimal. 
The angle can be interpreted as the extension of the previous joint. When the axis moves out of the green/red area of the purple arrow, the joint is out of angle.

**Comment by i-make-robots** [comment]
Closed without fixing?
